---
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Amplify Advent Calendar 2019"
Parameters:
  env:
    Type: "String"
    Description: "The environment name. e.g. Dev, Test, or Production"
    Default: "NONE"
Resources:
  AdventCalendar2019Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019Vpc-${env}"
  AdventCalendar2019VpcPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/18
      VpcId:
        Ref: AdventCalendar2019Vpc
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPublicSubnet1-${env}"
  AdventCalendar2019VpcPublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: AdventCalendar2019Vpc
  AdventCalendar2019VpcPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPublicSubnet1RouteTable
      SubnetId:
        Ref: AdventCalendar2019VpcPublicSubnet1
  AdventCalendar2019VpcPublicSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPublicSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: AdventCalendar2019VpcIGW
    DependsOn:
      - AdventCalendar2019VpcGW
  AdventCalendar2019VpcIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcIGW-${env}"
  AdventCalendar2019VpcGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: AdventCalendar2019Vpc
      InternetGatewayId:
        Ref: AdventCalendar2019VpcIGW
  AdventCalendar2019VpcPublicSubnet1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AdventCalendar2019VpcPublicSubnet1NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - AdventCalendar2019VpcPublicSubnet1EIP
          - AllocationId
      SubnetId:
        Ref: AdventCalendar2019VpcPublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPublicSubnet1NATGateway-${env}"
  AdventCalendar2019VpcPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.64.0/18
      VpcId:
        Ref: AdventCalendar2019Vpc
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPublicSubnet2-${env}"
  AdventCalendar2019VpcPublicSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: AdventCalendar2019Vpc
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPublicSubnet2RouteTable-${env}"
  AdventCalendar2019VpcPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPublicSubnet2RouteTable
      SubnetId:
        Ref: AdventCalendar2019VpcPublicSubnet2
  AdventCalendar2019VpcPublicSubnet2DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPublicSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: AdventCalendar2019VpcIGW
    DependsOn:
      - AdventCalendar2019VpcGW
  AdventCalendar2019VpcPublicSubnet2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  AdventCalendar2019VpcPublicSubnet2NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - AdventCalendar2019VpcPublicSubnet2EIP
          - AllocationId
      SubnetId:
        Ref: AdventCalendar2019VpcPublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPublicSubnet2NATGateway-${env}"
  AdventCalendar2019VpcPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/18
      VpcId:
        Ref: AdventCalendar2019Vpc
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPrivateSubnet1-${env}"
  AdventCalendar2019VpcPrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: AdventCalendar2019Vpc
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPrivateSubnet1RouteTable-${env}"
  AdventCalendar2019VpcPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPrivateSubnet1RouteTable
      SubnetId:
        Ref: AdventCalendar2019VpcPrivateSubnet1
  AdventCalendar2019VpcPrivateSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPrivateSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: AdventCalendar2019VpcPublicSubnet1NATGateway
  AdventCalendar2019VpcPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.192.0/18
      VpcId:
        Ref: AdventCalendar2019Vpc
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPrivateSubnet2-${env}"
  AdventCalendar2019VpcPrivateSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: AdventCalendar2019Vpc
      Tags:
        - Key: Name
          Value: !Sub "AdventCalendar2019VpcPrivateSubnet2RouteTable-${env}"
  AdventCalendar2019VpcPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPrivateSubnet2RouteTable
      SubnetId:
        Ref: AdventCalendar2019VpcPrivateSubnet2
  AdventCalendar2019VpcPrivateSubnet2DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: AdventCalendar2019VpcPrivateSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: AdventCalendar2019VpcPublicSubnet2NATGateway
  AdventCalendar2019Cluster:
    Type: AWS::ECS::Cluster
  AdventCalendar2019FargateServiceLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - Fn::GetAtt:
            - AdventCalendar2019FargateServiceLBSecurityGroup
            - GroupId
      Subnets:
        - Ref: AdventCalendar2019VpcPublicSubnet1
        - Ref: AdventCalendar2019VpcPublicSubnet2
      Type: application
    DependsOn:
      - AdventCalendar2019VpcPublicSubnet1DefaultRoute
      - AdventCalendar2019VpcPublicSubnet2DefaultRoute
  AdventCalendar2019FargateServiceLBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AdventCalendar2019FargateServiceLBSecurityGroup
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Allow from anyone on port 80
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId:
        Ref: AdventCalendar2019Vpc
  AdventCalendar2019FargateServiceLBSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt:
          - AdventCalendar2019FargateServiceLBSecurityGroup
          - GroupId
      IpProtocol: tcp
      Description: Load balancer to target
      DestinationSecurityGroupId:
        Fn::GetAtt:
          - AdventCalendar2019FargateServiceSecurityGroup
          - GroupId
      FromPort: 80
      ToPort: 80
  AdventCalendar2019FargateServiceLBPublicListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: AdventCalendar2019FargateServiceLBPublicListenerECSGroup
          Type: forward
      LoadBalancerArn:
        Ref: AdventCalendar2019FargateServiceLB
      Port: 80
      Protocol: HTTP
  AdventCalendar2019FargateServiceLBPublicListenerECSGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId:
        Ref: AdventCalendar2019Vpc
  AdventCalendar2019FargateServiceTaskDefTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
  AdventCalendar2019FargateServiceTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: amazon/amazon-ecs-sample
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: AdventCalendar2019FargateServiceTaskDefwebLogGroup
              awslogs-stream-prefix: MyFargateService
              awslogs-region:
                Ref: AWS::Region
          Name: web
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
      Cpu: "512"
      ExecutionRoleArn:
        Fn::GetAtt:
          - AdventCalendar2019FargateServiceTaskDefExecutionRole
          - Arn
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        Fn::GetAtt:
          - AdventCalendar2019FargateServiceTaskDefTaskRole
          - Arn
  AdventCalendar2019FargateServiceTaskDefwebLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  AdventCalendar2019FargateServiceTaskDefExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
  AdventCalendar2019FargateServiceTaskDefExecutionRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - AdventCalendar2019FargateServiceTaskDefwebLogGroup
                - Arn
        Version: "2012-10-17"
      PolicyName: AdventCalendar2019FargateServiceTaskDefExecutionRoleDefaultPolicy
      Roles:
        - Ref: AdventCalendar2019FargateServiceTaskDefExecutionRole
  AdventCalendar2019FargateService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition:
        Ref: AdventCalendar2019FargateServiceTaskDef
      Cluster:
        Ref: AdventCalendar2019Cluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: 6
      EnableECSManagedTags: false
      HealthCheckGracePeriodSeconds: 60
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: web
          ContainerPort: 80
          TargetGroupArn:
            Ref: AdventCalendar2019FargateServiceLBPublicListenerECSGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::GetAtt:
                - AdventCalendar2019FargateServiceSecurityGroup
                - GroupId
          Subnets:
            - Ref: AdventCalendar2019VpcPrivateSubnet1
            - Ref: AdventCalendar2019VpcPrivateSubnet2
    DependsOn:
      - AdventCalendar2019FargateServiceLBPublicListenerECSGroup
      - AdventCalendar2019FargateServiceLBPublicListener
  AdventCalendar2019FargateServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: CdkFargateStack/MyFargateService/Service/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId:
        Ref: AdventCalendar2019Vpc
  AdventCalendar2019FargateServiceSecurityGroupfromLBSecurityGroup:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      Description: Load balancer to target
      FromPort: 80
      GroupId:
        Fn::GetAtt:
          - AdventCalendar2019FargateServiceSecurityGroup
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - AdventCalendar2019FargateServiceLBSecurityGroup
          - GroupId
      ToPort: 80
